db_name: "i2b2"
db_password: "demouser"

crc_data_dir: "/opt/i2b2/data/edu.harvard.i2b2.data/Release_1-7/NewInstall/Crcdata/"
hive_data_dir: "/opt/i2b2/data/edu.harvard.i2b2.data/Release_1-7/NewInstall/Hivedata/"
im_data_dir: "/opt/i2b2/data/edu.harvard.i2b2.data/Release_1-7/NewInstall/Imdata/"
metadata_dir: "/opt/i2b2/data/edu.harvard.i2b2.data/Release_1-7/NewInstall/Metadata/"
pmdata_dir: "/opt/i2b2/data/edu.harvard.i2b2.data/Release_1-7/NewInstall/Pmdata/"
workdata_dir: "/opt/i2b2/data/edu.harvard.i2b2.data/Release_1-7/NewInstall/Workdata/"


dbs_list:
- dbuser: i2b2demodata
- dbuser: i2b2hive
- dbuser: i2b2imdata
- dbuser: i2b2metadata
- dbuser: i2b2pm
- dbuser: i2b2workdata
- dbuser: shrine_ont
